baseURL = "https://github.com/KunikaValecha/kunika_writes.github.io.git"
languageCode = "en-us"
title = "KUNIKA VALECHA"
theme = "ananke"
canonifyurls = true
resourceDir = "../resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
Copyright = "Kunika Valecha"
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]

description = "Enter your personal description"
authorlocation = "authorlocation"
cover = "/images/tech.png"
## save the image you want to use as background picture in directory "./static/images"author = "author name"(delete this line when editing)
logo = "images/logo.png"
## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)

hideHUGOSupport = true

  favicon = "/images/favicon.ico"
  site_logo = ""
  #description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/KunikaValecha"
  instagram = "https://www.instagram.com/kunikavalecha/"
  youtube = ""
  github = "https://github.com/KunikaValecha"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/kunikavalecha/"
  mastodon = ""
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/12003879/kunika-valecha"
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/tech.jpg"
  recent_posts_number = 2
theme = "ananke"

[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "Blog"
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/stories/post"
weight = 40

[[menu.main]]
name = "About"
identifier = "about" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/stories/about"
weight = 40




